In [ ]:
import json
import re
import sys
import warnings
from pathlib import Path

import pandas as pd

sys.path.insert(0, str((Path.cwd() / "src").resolve()))

from speech_recognition.config import (
    ALLOWED_EVALUATION_STRATEGIES,
    ALLOWED_FEATURE_PIPELINES,
    ALLOWED_MODEL_FAMILIES,
    ALLOWED_SCHEDULERS,
)

warnings.filterwarnings("ignore")

# Data load

In [2]:
def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


project_root = Path.cwd().resolve().parent
mlruns_dir = project_root / "mlruns" / "1"
run_dirs = sorted(path for path in mlruns_dir.iterdir() if path.is_dir())

per_class_rows = []
eval_rows = []

for run_dir in run_dirs:
    run_id = run_dir.name
    artifact_dir = run_dir / "artifacts"
    payload_path = artifact_dir / "run_payload.json"

    # eval data: payload metrics
    if payload_path.exists():
        payload = load_json(payload_path)
        metrics = payload.get("metrics", {})
        checkpoint_path = payload.get("checkpoint_path", "")

        eval_rows.append(
            {
                "run_id": run_id,
                "phase": payload.get("phase"),
                "metric_phase": payload.get("metric_phase"),
                "epoch": payload.get("epoch"),
                "step": payload.get("step"),
                "checkpoint_path": checkpoint_path,
                "macro_f1": metrics.get("macro_f1"),
                "command_macro_f1": metrics.get("command_macro_f1"),
                "core_command_macro_f1": metrics.get("core_command_macro_f1"),
                "unknown_f1": metrics.get("unknown_f1"),
                "silence_f1": metrics.get("silence_f1"),
                "macro_f1_nc": metrics.get("macro_f1_nc"),
                "unknown_to_command_leakage": metrics.get("unknown_to_command_leakage"),
                "silence_false_trigger_rate": metrics.get("silence_false_trigger_rate"),
            }
        )

        # per-class eval data
        for class_name, class_scores in metrics.get("per_class", {}).items():
            per_class_rows.append(
                {
                    "run_id": run_id,
                    "phase": payload.get("phase"),
                    "class_name": class_name,
                    "precision": class_scores.get("precision"),
                    "recall": class_scores.get("recall"),
                    "f1": class_scores.get("f1"),
                }
            )


df_eval = pd.DataFrame(eval_rows)
df_per_class = pd.DataFrame(per_class_rows)

if not df_eval.empty:
    df_eval = df_eval.sort_values("run_id").reset_index(drop=True)
if not df_per_class.empty:
    df_per_class = df_per_class.sort_values(["run_id", "class_name"]).reset_index(drop=True)


print(f"\nEval metrics ({len(df_eval)} runs):")
display(df_eval.head())
print(f"\nPer-class metrics ({len(df_per_class)} rows):")
display(df_per_class.head(12))

Eval metrics (136 runs):

,run_id,phase,metric_phase,epoch,step,checkpoint_path,macro_f1,command_macro_f1,core_command_macro_f1,unknown_f1,silence_f1,macro_f1_nc,unknown_to_command_leakage,silence_false_trigger_rate
0,01efede02143439c83433645c1e7a778,phase_1,val,55,17215,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.540173,0.648208,0.648208,0.0,0.0,0.0,0.0,0.0
1,033d62c906e540649556d75c60108531,phase_3,val,26,8138,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.669277,0.803132,0.803132,0.0,0.0,0.0,0.0,0.0
2,0b202ae436594c23b2fe330844f70eb3,phase_3,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0
3,113b2e8c8a6e404890dea59f78c58804,None,val,13,15535,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.0,0.0,0.0,1.0,1.0
4,115f6389b4e543c0b8cd6cf0bfe3f173,phase_3,val,53,16589,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.697054,0.836465,0.836465,0.0,0.0,0.0,0.0,0.0

Per-class metrics (1632 rows):

,run_id,phase,class_name,precision,recall,f1
0,01efede02143439c83433645c1e7a778,phase_1,__silence__,0.000000,0.000,0.000000
1,01efede02143439c83433645c1e7a778,phase_1,__unknown__,0.000000,0.000,0.000000
2,01efede02143439c83433645c1e7a778,phase_1,down,0.552632,0.504,0.527197
3,01efede02143439c83433645c1e7a778,phase_1,go,0.527778,0.456,0.489270
4,01efede02143439c83433645c1e7a778,phase_1,left,0.655797,0.724,0.688213
5,01efede02143439c83433645c1e7a778,phase_1,no,0.683594,0.700,0.691700
6,01efede02143439c83433645c1e7a778,phase_1,off,0.593548,0.368,0.454321
7,01efede02143439c83433645c1e7a778,phase_1,on,0.479109,0.688,0.564860
8,01efede02143439c83433645c1e7a778,phase_1,right,0.660000,0.660,0.660000
9,01efede02143439c83433645c1e7a778,phase_1,stop,0.937500,0.840,0.886076
10,01efede02143439c83433645c1e7a778,phase_1,up,0.735714,0.824,0.777358
11,01efede02143439c83433645c1e7a778,phase_1,yes,0.734375,0.752,0.743083

# Fill phase column

In [3]:
def fill_phase(row):
    if "phase" in row and pd.notna(row["phase"]):
        return row["phase"]

    match = re.search(r"phase_(\d+)", row["checkpoint_path"])
    if match:
        return f"phase_{match.group(1)}"
    return None


df_eval["phase"] = df_eval.apply(
    lambda row: fill_phase(row),
    axis=1,
)

df_per_class = df_per_class.drop(columns=["phase"]).merge(
    df_eval[["run_id", "phase"]],
    on="run_id",
    how="left",
)

df_eval.phase.isna().sum(), df_per_class.phase.isna().sum()

(np.int64(0), np.int64(0))

# Config extraction

In [4]:
def extract_trial_config(checkpoint_path: str) -> str:
    """Extract trial config name from checkpoint path."""
    if not checkpoint_path or pd.isna(checkpoint_path):
        return None
    parts = checkpoint_path.split("/runs/")
    if len(parts) == 2:
        remainder = parts[1]
        return remainder.split("/")[0]
    return None


def extract_trial_seed(trial_config: str) -> int:
    """Extract seed from trial config."""
    if not trial_config or pd.isna(trial_config):
        return None
    match = re.search(r"_seed_(\d+)$", trial_config)
    return int(match.group(1)) if match else None


def extract_config_middle(trial_config: str) -> str:
    """Extract config string (everything between trial_XX_ and _seed_)."""
    if not trial_config or pd.isna(trial_config):
        return None
    match = re.search(r"^trial_\d+_(.*)_seed_\d+$", trial_config)
    return match.group(1) if match else None


df_eval["trial_config"] = df_eval["checkpoint_path"].apply(extract_trial_config)
df_eval["trial_seed"] = df_eval["trial_config"].apply(extract_trial_seed)
df_eval["config_str"] = df_eval["trial_config"].apply(extract_config_middle)

print(f"Extracted trial configs: {df_eval['trial_config'].notna().sum()} / {len(df_eval)}")
display(df_eval[["run_id", "trial_config", "trial_seed", "config_str"]].head(15))

Extracted trial configs: 136 / 136

,run_id,trial_config,trial_seed,config_str
0,01efede02143439c83433645c1e7a778,trial_30_mel_specaugment_xlstm_seed_2003,2003,mel_specaugment_xlstm
1,033d62c906e540649556d75c60108531,trial_13_ast_linear_interp_dropout_0.5_seed_42,42,ast_linear_interp_dropout_0.5
2,0b202ae436594c23b2fe330844f70eb3,trial_07_ast_mlp_256_interp_dropout_0.5_seed_0,0,ast_mlp_256_interp_dropout_0.5
3,113b2e8c8a6e404890dea59f78c58804,trial_01_two_stage_detector_trial_01_ast_linea...,0,two_stage_detector_trial_01_ast_linear_interp_...
4,115f6389b4e543c0b8cd6cf0bfe3f173,trial_19_ast_mlp_256_interp_dropout_0.1_seed_2003,2003,ast_mlp_256_interp_dropout_0.1
5,11b114a41d564f359864dff904b4eaa2,trial_05_mlp_mixer_dropout_0.0_head_l2_True_se...,42,mlp_mixer_dropout_0.0_head_l2_True
6,149eaa36d2a84307a6842b61aa6819ff,trial_11_high_temporal_mel_xlstm_seed_42,42,high_temporal_mel_xlstm
7,19915d2065c84ec385cdc2a18e6e3744,trial_04_convnext_sd_0.2_kernel_7_seed_42,42,convnext_sd_0.2_kernel_7
8,1e7c001bf663478fbd092a6b3dcb4f13,trial_08_two_stage_detector_trial_01_mlp_mixer...,42,two_stage_detector_trial_01_mlp_mixer_dropout_...
9,2262c543024b4282ba8833a582d0ca2c,trial_04_sampling_control_trial_01_convnext_sd...,0,sampling_control_trial_01_convnext_sd_0.0_kern...
10,29a88ff4404440b79d09cd58fe294c35,trial_03_two_stage_detector_trial_01_ast_linea...,2003,two_stage_detector_trial_01_ast_linear_interp_...
11,2ab50f05c7b94b57bdadc022859cdab5,trial_17_ast_linear_interp_dropout_0.1_seed_2003,2003,ast_linear_interp_dropout_0.1
12,2af2e43a256b42f59c31af2ff5589527,trial_22_mel_spectrogram_xlstm_reduce_on_plate...,0,mel_spectrogram_xlstm_reduce_on_plateau_wd_0.1
13,2ba9be28e54b4aefb6daf6983a7a66e7,trial_10_mel_spectrogram_xlstm_reduce_on_plate...,0,mel_spectrogram_xlstm_reduce_on_plateau_wd_0.01
14,2bb7d8cb9a5f4eb2a461e9a6a9d97c13,trial_07_mel_spectrogram_convnext_reduce_on_pl...,0,mel_spectrogram_convnext_reduce_on_plateau_wd_...

In [5]:
df1 = df_eval[df_eval["phase"] == "phase_1"]
df2 = df_eval[df_eval["phase"] == "phase_2"]
df3 = df_eval[df_eval["phase"] == "phase_3"]
df4 = df_eval[df_eval["phase"] == "phase_4"]

## Phase 1

In [6]:
df1["config_str"].unique()

array(['mel_specaugment_xlstm', 'high_temporal_mel_xlstm',
       'mel_specaugment_convnext', 'mfcc_convnext',
       'mel_spectrogram_xlstm', 'mel_spectrogram_convnext',
       'pcen_convnext', 'mfcc_xlstm', 'pcen_xlstm',
       'high_temporal_mel_convnext'], dtype=object)

In [7]:
df1["feature_pipeline"] = df1["config_str"].apply(
    lambda s: next((feat for feat in ALLOWED_FEATURE_PIPELINES if feat in s), None)
)
df1["model_family"] = df1["config_str"].apply(
    lambda s: next((family for family in ALLOWED_MODEL_FAMILIES if family in s), None)
)

In [8]:
df1

,run_id,phase,metric_phase,epoch,step,checkpoint_path,macro_f1,command_macro_f1,core_command_macro_f1,unknown_f1,silence_f1,macro_f1_nc,unknown_to_command_leakage,silence_false_trigger_rate,trial_config,trial_seed,config_str,feature_pipeline,model_family
0,01efede02143439c83433645c1e7a778,phase_1,val,55,17215,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.540173,0.648208,0.648208,0.0,0.0,0.0,0.0,0.0,trial_30_mel_specaugment_xlstm_seed_2003,2003,mel_specaugment_xlstm,mel_specaugment,xlstm
6,149eaa36d2a84307a6842b61aa6819ff,phase_1,val,56,17528,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.330772,0.396927,0.396927,0.0,0.0,0.0,0.0,0.0,trial_11_high_temporal_mel_xlstm_seed_42,42,high_temporal_mel_xlstm,high_temporal_mel,xlstm
17,3466252bf2fa4efc98095ac1322965d1,phase_1,val,41,12833,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.320741,0.384889,0.384889,0.0,0.0,0.0,0.0,0.0,trial_12_high_temporal_mel_xlstm_seed_2003,2003,high_temporal_mel_xlstm,high_temporal_mel,xlstm
25,3b75b67d724e4212a29e17382cd38a60,phase_1,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_27_mel_specaugment_convnext_seed_2003,2003,mel_specaugment_convnext,mel_specaugment,convnext
32,42852d78afab48d5a52a795e9067b4dd,phase_1,val,31,9703,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.703280,0.843936,0.843936,0.0,0.0,0.0,0.0,0.0,trial_13_mfcc_convnext_seed_0,0,mfcc_convnext,mfcc,convnext
36,52e2061ed18448a6816fd198038c6393,phase_1,val,38,11894,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.544402,0.653282,0.653282,0.0,0.0,0.0,0.0,0.0,trial_04_mel_spectrogram_xlstm_seed_0,0,mel_spectrogram_xlstm,mel_spectrogram,xlstm
44,6075167b17294671862e1a61a5c9a645,phase_1,val,45,14085,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.540905,0.649086,0.649086,0.0,0.0,0.0,0.0,0.0,trial_05_mel_spectrogram_xlstm_seed_42,42,mel_spectrogram_xlstm,mel_spectrogram,xlstm
55,6e9114cac7114cbdb933a64ccca94e92,phase_1,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_26_mel_specaugment_convnext_seed_42,42,mel_specaugment_convnext,mel_specaugment,convnext
57,7146b327267b437c93c3a36a58260666,phase_1,val,51,15963,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.740798,0.888958,0.888958,0.0,0.0,0.0,0.0,0.0,trial_03_mel_spectrogram_convnext_seed_2003,2003,mel_spectrogram_convnext,mel_spectrogram,convnext
61,738b4d7ea6cd4d3182d604153a184768,phase_1,val,43,13459,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.343172,0.411806,0.411806,0.0,0.0,0.0,0.0,0.0,trial_10_high_temporal_mel_xlstm_seed_0,0,high_temporal_mel_xlstm,high_temporal_mel,xlstm
62,76a0066d9a064629894ab368e97fc2ba,phase_1,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_21_pcen_convnext_seed_2003,2003,pcen_convnext,pcen,convnext
63,76c1b9072c8743e59fc74006608014e9,phase_1,val,53,16589,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.746316,0.895580,0.895580,0.0,0.0,0.0,0.0,0.0,trial_02_mel_spectrogram_convnext_seed_42,42,mel_spectrogram_convnext,mel_spectrogram,convnext
64,79a3537fcc08486d99a0123827a91217,phase_1,val,57,17841,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.156756,0.188107,0.188107,0.0,0.0,0.0,0.0,0.0,trial_18_mfcc_xlstm_seed_2003,2003,mfcc_xlstm,mfcc,xlstm
65,7a09d052c24942c6a393a87bd2dd2f63,phase_1,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_24_pcen_xlstm_seed_2003,2003,pcen_xlstm,pcen,xlstm
67,7b82d8c70bc641c280efd3e7f4867e7b,phase_1,val,54,16902,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.532142,0.638571,0.638571,0.0,0.0,0.0,0.0,0.0,trial_04_mel_spectrogram_xlstm_seed_0,0,mel_spectrogram_xlstm,mel_spectrogram,xlstm
71,7dc9bcdabf3b4d6a9b5c6abafb9b0da2,phase_1,val,33,10329,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.733753,0.880503,0.880503,0.0,0.0,0.0,0.0,0.0,trial_01_mel_spectrogram_convnext_seed_0,0,mel_spectrogram_convnext,mel_spectrogram,convnext
72,831bd0a75a684592af6e37cfd6f1eb34,phase_1,val,51,15963,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.194934,0.233921,0.233921,0.0,0.0,0.0,0.0,0.0,trial_17_mfcc_xlstm_seed_42,42,mfcc_xlstm,mfcc,xlstm
75,85d763c65848415aaddd0cb99d5daa59,phase_1,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_22_pcen_xlstm_seed_0,0,pcen_xlstm,pcen,xlstm
81,93dcad13d22a42acacd829e7afed1d75,phase_1,val,40,12520,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.544212,0.653054,0.653054,0.0,0.0,0.0,0.0,0.0,trial_05_mel_spectrogram_xlstm_seed_42,42,mel_spectrogram_xlstm,mel_spectrogram,xlstm
82,9488e5d5be5f4e3d8df286c20aedd9dd,phase_1,val,56,17528,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_28_mel_specaugment_xlstm_seed_0,0,mel_specaugment_xlstm,mel_specaugment,xlstm
84,9532e268048d4696913054a0721011b8,phase_1,val,67,20971,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.742973,0.891567,0.891567,0.0,0.0,0.0,0.0,0.0,trial_02_mel_spectrogram_convnext_seed_42,42,mel_spectrogram_convnext,mel_spectrogram,convnext
87,9f94aef025ee43cea8bb1557e181a0de,phase_1,val,51,15963,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.712389,0.854866,0.854866,0.0,0.0,0.0,0.0,0.0,trial_14_mfcc_convnext_seed_42,42,mfcc_convnext,mfcc,convnext
88,a01640073ed749dcb5fa4d0a32c4e558,phase_1,val,54,16902,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_29_mel_specaugment_xlstm_seed_42,42,mel_specaugment_xlstm,mel_specaugment,xlstm
89,a2cad986dfa84aa9a861ce888c69c2eb,phase_1,val,37,11581,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.549535,0.659442,0.659442,0.0,0.0,0.0,0.0,0.0,trial_08_high_temporal_mel_convnext_seed_42,42,high_temporal_mel_convnext,high_temporal_mel,convnext
91,a5e24c8c76ce45a090c482359e495733,phase_1,val,86,26918,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.754751,0.905701,0.905701,0.0,0.0,0.0,0.0,0.0,trial_01_mel_spectrogram_convnext_seed_0,0,mel_spectrogram_convnext,mel_spectrogram,convnext
92,a62a513df58a41658b0e52e4cb85491a,phase_1,val,41,12833,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.534509,0.641411,0.641411,0.0,0.0,0.0,0.0,0.0,trial_06_mel_spectrogram_xlstm_seed_2003,2003,mel_spectrogram_xlstm,mel_spectrogram,xlstm
93,a7783fced54f47d3acf42ac0785eb28a,phase_1,val,23,7199,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.554346,0.665215,0.665215,0.0,0.0,0.0,0.0,0.0,trial_09_high_temporal_mel_convnext_seed_2003,2003,high_temporal_mel_convnext,high_temporal_mel,convnext
98,b1325a6b53ab47adb795f30db8eebf44,phase_1,val,43,13459,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.538638,0.646365,0.646365,0.0,0.0,0.0,0.0,0.0,trial_07_high_temporal_mel_convnext_seed_0,0,high_temporal_mel_convnext,high_temporal_mel,convnext
99,b4bf8507b9974137ac0de4ff00f6cb3b,phase_1,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_25_mel_specaugment_convnext_seed_0,0,mel_specaugment_convnext,mel_specaugment,convnext
103,bb5a1ee39e1d4171ac25878d0bf29b97,phase_1,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_19_pcen_convnext_seed_0,0,pcen_convnext,pcen,convnext
105,c4a88dcb89d34965aafdc3fd9b9d9493,phase_1,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,0.0,0.0,0.0,0.0,trial_20_pcen_convnext_seed_42,42,pcen_convnext,pcen,convnext
114,de6ed9935cb542f6ab4228d30bbc972c,phase_1,val,74,23162,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.714215,0.857058,0.857058,0.0,0.0,0.0,0.0,0.0,trial_15_mfcc_convnext_seed_2003,2003,mfcc_convnext,mfcc,convnext
116,e72fdb0a0de8424bb4b7d74f952f79e9,phase_1,val,62,19406,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.745813,0.894975,0.894975,0.0,0.0,0.0,0.0,0.0,trial_03_mel_spectrogram_convnext_seed_2003,2003,mel_spectrogram_convnext,mel_spectrogram,convnext
125,f33816b8260a404595ec7613c0dfa9b0,phase_1,val,21,6573,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.018756,0.022507,0.022507,0.0,0.0,0.0,0.0,0.0,trial_23_pcen_xlstm_seed_42,42,pcen_xlstm,pcen,xlstm
129,f93939b06c5743c68fb5cebbcf961b70,phase_1,val,25,7825,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.054828,0.065793,0.065793,0.0,0.0,0.0,0.0,0.0,trial_16_mfcc_xlstm_seed_0,0,mfcc_xlstm,mfcc,xlstm

## Phase 2

In [9]:
df2.config_str.unique()

array(['mel_spectrogram_xlstm_reduce_on_plateau_wd_0.1',
       'mel_spectrogram_xlstm_reduce_on_plateau_wd_0.01',
       'mel_spectrogram_convnext_reduce_on_plateau_wd_0.01',
       'mel_spectrogram_xlstm_cosine_annealing_warmup_wd_0.01',
       'mel_spectrogram_xlstm_cosine_annealing_warmup_wd_0.1',
       'mel_spectrogram_convnext_cosine_annealing_warmup_wd_0.1',
       'mel_spectrogram_convnext_cosine_annealing_warmup_wd_0.01',
       'mel_spectrogram_convnext_reduce_on_plateau_wd_0.1'], dtype=object)

In [10]:
df2["feature_pipeline"] = "mel_spectrogram"
df2["model_family"] = df2["config_str"].apply(
    lambda s: next((family for family in ALLOWED_MODEL_FAMILIES if f"_{family}_" in s), None)
)

df2["weight_decay"] = df2["config_str"].apply(
    lambda s: ".".join(re.search(r"wd_(\d+).(\d+)", s).groups())
)

df2["scheduler"] = df2["config_str"].apply(
    lambda s: next((scheduler for scheduler in ALLOWED_SCHEDULERS if f"_{scheduler}_" in s), None)
)

## Phase 3

In [11]:
df3.config_str.unique()

array(['ast_linear_interp_dropout_0.5', 'ast_mlp_256_interp_dropout_0.5',
       'ast_mlp_256_interp_dropout_0.1',
       'mlp_mixer_dropout_0.0_head_l2_True', 'convnext_sd_0.2_kernel_7',
       'ast_linear_interp_dropout_0.1',
       'mlp_mixer_dropout_0.2_head_l2_False',
       'ast_mlp_256_learned_dropout_0.1',
       'ast_linear_learned_dropout_0.5', 'ast_linear_learned_dropout_0.1',
       'mlp_mixer_dropout_0.2_head_l2_True',
       'mlp_mixer_dropout_0.0_head_l2_False',
       'ast_mlp_256_learned_dropout_0.5', 'convnext_sd_0.0_kernel_7'],
      dtype=object)

In [12]:
AST_HEAD = ["linear", "mlp_256"]
AST_EMB = ["interp", "learned"]

In [13]:
df3["model_family"] = df3["config_str"].apply(
    lambda s: next((family for family in ALLOWED_MODEL_FAMILIES if f"{family}" in s), None)
)

df3["ast_head"] = df3["config_str"].apply(
    lambda s: next((head for head in AST_HEAD if f"{head}" in s), None)
)

df3["ast_embedding"] = df3["config_str"].apply(
    lambda s: next((emb for emb in AST_EMB if f"{emb}" in s), None)
)

df3["dropout"] = df3["config_str"].apply(
    lambda s: (".".join(re.search(r"dropout_(\d+).(\d+)", s).groups()) if "dropout_" in s else None)
)

df3["kernel_size"] = df3["config_str"].apply(
    lambda s: re.search(r"kernel_(\d+)", s).group(1) if "kernel_" in s else None
)

df3["sd"] = df3["config_str"].apply(
    lambda s: ".".join(re.search(r"sd_(\d+).(\d+)", s).groups()) if "sd_" in s else None
)

df3["head_l2"] = df3["config_str"].apply(
    lambda s: True if "head_l2_True" in s else False if "head_l2_False" in s else None
)

In [14]:
df3

,run_id,phase,metric_phase,epoch,step,checkpoint_path,macro_f1,command_macro_f1,core_command_macro_f1,unknown_f1,...,trial_config,trial_seed,config_str,model_family,ast_head,ast_embedding,dropout,kernel_size,sd,head_l2
1,033d62c906e540649556d75c60108531,phase_3,val,26,8138,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.669277,0.803132,0.803132,0.0,...,trial_13_ast_linear_interp_dropout_0.5_seed_42,42,ast_linear_interp_dropout_0.5,ast,linear,interp,0.5,None,None,None
2,0b202ae436594c23b2fe330844f70eb3,phase_3,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_07_ast_mlp_256_interp_dropout_0.5_seed_0,0,ast_mlp_256_interp_dropout_0.5,ast,mlp_256,interp,0.5,None,None,None
4,115f6389b4e543c0b8cd6cf0bfe3f173,phase_3,val,53,16589,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.697054,0.836465,0.836465,0.0,...,trial_19_ast_mlp_256_interp_dropout_0.1_seed_2003,2003,ast_mlp_256_interp_dropout_0.1,ast,mlp_256,interp,0.1,None,None,None
5,11b114a41d564f359864dff904b4eaa2,phase_3,val,17,5321,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.050761,0.060913,0.060913,0.0,...,trial_05_mlp_mixer_dropout_0.0_head_l2_True_se...,42,mlp_mixer_dropout_0.0_head_l2_True,mlp_mixer,None,None,0.0,None,None,True
7,19915d2065c84ec385cdc2a18e6e3744,phase_3,val,67,20971,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.746239,0.895487,0.895487,0.0,...,trial_04_convnext_sd_0.2_kernel_7_seed_42,42,convnext_sd_0.2_kernel_7,convnext,None,None,None,7,0.2,None
11,2ab50f05c7b94b57bdadc022859cdab5,phase_3,val,39,12207,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.680569,0.816683,0.816683,0.0,...,trial_17_ast_linear_interp_dropout_0.1_seed_2003,2003,ast_linear_interp_dropout_0.1,ast,linear,interp,0.1,None,None,None
15,2e2c821c93e34b00b56b686ce5c603fd,phase_3,val,68,21284,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.707229,0.848674,0.848674,0.0,...,trial_05_ast_linear_interp_dropout_0.5_seed_0,0,ast_linear_interp_dropout_0.5,ast,linear,interp,0.5,None,None,None
19,380427c82674437f81f6f84af04d5a05,phase_3,val,28,8764,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.722047,0.866456,0.866456,0.0,...,trial_08_mlp_mixer_dropout_0.2_head_l2_False_s...,42,mlp_mixer_dropout_0.2_head_l2_False,mlp_mixer,None,None,0.2,None,None,False
22,39b13dbb89bc41ee972420168cac5995,phase_3,val,36,11268,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.687695,0.825234,0.825234,0.0,...,trial_04_ast_mlp_256_learned_dropout_0.1_seed_0,0,ast_mlp_256_learned_dropout_0.1,ast,mlp_256,learned,0.1,None,None,None
24,3ae7ad287cc74928aceb5e17e767e804,phase_3,val,40,12520,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.690900,0.829081,0.829081,0.0,...,trial_22_ast_linear_learned_dropout_0.5_seed_2003,2003,ast_linear_learned_dropout_0.5,ast,linear,learned,0.5,None,None,None
29,3d9167a123c0445cb79291e1c56bcc83,phase_3,val,30,9390,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.685238,0.822286,0.822286,0.0,...,trial_10_ast_linear_learned_dropout_0.1_seed_42,42,ast_linear_learned_dropout_0.1,ast,linear,learned,0.1,None,None,None
30,3efa42f9b81844f091a4e52f86ee6374,phase_3,val,30,9390,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.685238,0.822286,0.822286,0.0,...,trial_09_ast_linear_interp_dropout_0.1_seed_42,42,ast_linear_interp_dropout_0.1,ast,linear,interp,0.1,None,None,None
31,3fcb5b09edf14ab4b639cdca5dfe0301,phase_3,val,26,8138,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.669277,0.803132,0.803132,0.0,...,trial_14_ast_linear_learned_dropout_0.5_seed_42,42,ast_linear_learned_dropout_0.5,ast,linear,learned,0.5,None,None,None
34,477bf2a985dc4da6b662dafc0ef8a10e,phase_3,val,13,4069,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.061920,0.074304,0.074304,0.0,...,trial_07_mlp_mixer_dropout_0.2_head_l2_True_se...,42,mlp_mixer_dropout_0.2_head_l2_True,mlp_mixer,None,None,0.2,None,None,True
35,5108a08f4a3f408b893e286568a5596f,phase_3,val,53,16589,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.697054,0.836465,0.836465,0.0,...,trial_20_ast_mlp_256_learned_dropout_0.1_seed_...,2003,ast_mlp_256_learned_dropout_0.1,ast,mlp_256,learned,0.1,None,None,None
37,54c359067afb4e93a109591e8a9e92e8,phase_3,val,39,12207,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.680569,0.816683,0.816683,0.0,...,trial_18_ast_linear_learned_dropout_0.1_seed_2003,2003,ast_linear_learned_dropout_0.1,ast,linear,learned,0.1,None,None,None
38,557a074138c74c34a451e06d7805f460,phase_3,val,50,15650,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_04_mlp_mixer_dropout_0.2_head_l2_False_s...,0,mlp_mixer_dropout_0.2_head_l2_False,mlp_mixer,None,None,0.2,None,None,False
39,560b5bbd206a4256a2aee738a944001a,phase_3,val,14,4382,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_06_mlp_mixer_dropout_0.0_head_l2_False_s...,42,mlp_mixer_dropout_0.0_head_l2_False,mlp_mixer,None,None,0.0,None,None,False
41,5bf218a50f9c4ef58a10c6c104aea841,phase_3,val,13,4069,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_09_mlp_mixer_dropout_0.0_head_l2_True_se...,2003,mlp_mixer_dropout_0.0_head_l2_True,mlp_mixer,None,None,0.0,None,None,True
47,62d07b86be72403bb037f3bce4561d06,phase_3,val,36,11268,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.687695,0.825234,0.825234,0.0,...,trial_03_ast_mlp_256_interp_dropout_0.1_seed_0,0,ast_mlp_256_interp_dropout_0.1,ast,mlp_256,interp,0.1,None,None,None
48,634054262aee4313b421dd8ce0d76d28,phase_3,val,49,15337,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.656512,0.787815,0.787815,0.0,...,trial_15_ast_mlp_256_interp_dropout_0.5_seed_42,42,ast_mlp_256_interp_dropout_0.5,ast,mlp_256,interp,0.5,None,None,None
51,65ec5f61b6ce445dabb7a42a4eca62c5,phase_3,val,78,24414,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.699127,0.838952,0.838952,0.0,...,trial_11_ast_mlp_256_interp_dropout_0.1_seed_42,42,ast_mlp_256_interp_dropout_0.1,ast,mlp_256,interp,0.1,None,None,None
60,729ceeb447a04efd86961dc5899d58d2,phase_3,val,53,16589,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.747840,0.897408,0.897408,0.0,...,trial_02_convnext_sd_0.2_kernel_7_seed_0,0,convnext_sd_0.2_kernel_7,convnext,None,None,None,7,0.2,None
66,7a71143b459e40489bf9afb13321f22e,phase_3,val,29,9077,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_03_mlp_mixer_dropout_0.2_head_l2_True_se...,0,mlp_mixer_dropout_0.2_head_l2_True,mlp_mixer,None,None,0.2,None,None,True
73,8332bfc0057449ad83da7516bf7b2011,phase_3,val,49,15337,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.656512,0.787815,0.787815,0.0,...,trial_16_ast_mlp_256_learned_dropout_0.5_seed_42,42,ast_mlp_256_learned_dropout_0.5,ast,mlp_256,learned,0.5,None,None,None
76,864033519ecf48828a36fe7160ce2112,phase_3,val,67,20971,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.746239,0.895487,0.895487,0.0,...,trial_03_convnext_sd_0.0_kernel_7_seed_42,42,convnext_sd_0.0_kernel_7,convnext,None,None,None,7,0.0,None
80,8da6736daa1c420f928f45aa29eba400,phase_3,val,53,16589,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.693455,0.832146,0.832146,0.0,...,trial_02_ast_linear_learned_dropout_0.1_seed_0,0,ast_linear_learned_dropout_0.1,ast,linear,learned,0.1,None,None,None
85,964cd66f82b94b3fb0fb75ee0658600b,phase_3,val,40,12520,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.690900,0.829081,0.829081,0.0,...,trial_21_ast_linear_interp_dropout_0.5_seed_2003,2003,ast_linear_interp_dropout_0.5,ast,linear,interp,0.5,None,None,None
86,980bd5b19af0420ca9e36924e2ea59cd,phase_3,val,40,12520,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.684446,0.821335,0.821335,0.0,...,trial_23_ast_mlp_256_interp_dropout_0.5_seed_2003,2003,ast_mlp_256_interp_dropout_0.5,ast,mlp_256,interp,0.5,None,None,None
90,a425ebc32bac4501ad74a5a37084ee22,phase_3,val,23,7199,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.735083,0.882100,0.882100,0.0,...,trial_05_convnext_sd_0.0_kernel_7_seed_2003,2003,convnext_sd_0.0_kernel_7,convnext,None,None,None,7,0.0,None
102,b7e578c51f7b41fd8003945a37f1a398,phase_3,val,14,4382,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_10_mlp_mixer_dropout_0.0_head_l2_False_s...,2003,mlp_mixer_dropout_0.0_head_l2_False,mlp_mixer,None,None,0.0,None,None,False
106,c52d2e6905c84cbca8e349943750e052,phase_3,val,33,10329,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.728884,0.874661,0.874661,0.0,...,trial_12_mlp_mixer_dropout_0.2_head_l2_False_s...,2003,mlp_mixer_dropout_0.2_head_l2_False,mlp_mixer,None,None,0.2,None,None,False
109,c83f004dca274c368dd253953533cb6b,phase_3,val,45,14085,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.053267,0.063920,0.063920,0.0,...,trial_11_mlp_mixer_dropout_0.2_head_l2_True_se...,2003,mlp_mixer_dropout_0.2_head_l2_True,mlp_mixer,None,None,0.2,None,None,True
110,c97ec8054f9c46e8b7d908c6e6e3ff71,phase_3,val,68,21284,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.707229,0.848674,0.848674,0.0,...,trial_06_ast_linear_learned_dropout_0.5_seed_0,0,ast_linear_learned_dropout_0.5,ast,linear,learned,0.5,None,None,None
111,ce14150d5b0346e194ed66662b962372,phase_3,val,53,16589,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.693455,0.832146,0.832146,0.0,...,trial_01_ast_linear_interp_dropout_0.1_seed_0,0,ast_linear_interp_dropout_0.1,ast,linear,interp,0.1,None,None,None
112,d20191afb1b54a3c943b80de33d44c5b,phase_3,val,53,16589,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.747840,0.897408,0.897408,0.0,...,trial_01_convnext_sd_0.0_kernel_7_seed_0,0,convnext_sd_0.0_kernel_7,convnext,None,None,None,7,0.0,None
119,eb4a33eaf21e4a51a7978658a95d82f8,phase_3,val,12,3756,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_01_mlp_mixer_dropout_0.0_head_l2_True_se...,0,mlp_mixer_dropout_0.0_head_l2_True,mlp_mixer,None,None,0.0,None,None,True
120,eca1c8865bd74a94a5ada28e8aa97a62,phase_3,val,40,12520,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.684446,0.821335,0.821335,0.0,...,trial_24_ast_mlp_256_learned_dropout_0.5_seed_...,2003,ast_mlp_256_learned_dropout_0.5,ast,mlp_256,learned,0.5,None,None,None
123,ef6cc20222a14f31b17e27bece61cd3d,phase_3,val,11,3443,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_08_ast_mlp_256_learned_dropout_0.5_seed_0,0,ast_mlp_256_learned_dropout_0.5,ast,mlp_256,learned,0.5,None,None,None
127,f517428595384cf986d9b9d097d248b3,phase_3,val,78,24414,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.699127,0.838952,0.838952,0.0,...,trial_12_ast_mlp_256_learned_dropout_0.1_seed_42,42,ast_mlp_256_learned_dropout_0.1,ast,mlp_256,learned,0.1,None,None,None
128,f5303a6c157546feab8791c35453dc71,phase_3,val,23,7199,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.735083,0.882100,0.882100,0.0,...,trial_06_convnext_sd_0.2_kernel_7_seed_2003,2003,convnext_sd_0.2_kernel_7,convnext,None,None,None,7,0.2,None
130,fa9f075042b2432c8fea49472173af7e,phase_3,val,14,4382,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.015152,0.018182,0.018182,0.0,...,trial_02_mlp_mixer_dropout_0.0_head_l2_False_s...,0,mlp_mixer_dropout_0.0_head_l2_False,mlp_mixer,None,None,0.0,None,None,False

## Phase 4

In [15]:
df4.config_str.unique()

array(['two_stage_detector_trial_01_ast_linear_interp_dropout_0.1_seed_0',
       'two_stage_detector_trial_01_mlp_mixer_dropout_0.0_head_l2_True_seed_0',
       'sampling_control_trial_01_convnext_sd_0.0_kernel_7_seed_0',
       'loss_reweighting_trial_01_convnext_sd_0.0_kernel_7_seed_0',
       'two_stage_detector_trial_01_convnext_sd_0.0_kernel_7_seed_0',
       'sampling_control_trial_01_ast_linear_interp_dropout_0.1_seed_0',
       'loss_reweighting_trial_01_ast_linear_interp_dropout_0.1_seed_0',
       'loss_reweighting_trial_01_mlp_mixer_dropout_0.0_head_l2_True_seed_0',
       'flat_multiclass_trial_01_ast_linear_interp_dropout_0.1_seed_0',
       'flat_multiclass_trial_01_convnext_sd_0.0_kernel_7_seed_0',
       'flat_multiclass_trial_01_mlp_mixer_dropout_0.0_head_l2_True_seed_0',
       'sampling_control_trial_01_mlp_mixer_dropout_0.0_head_l2_True_seed_0'],
      dtype=object)

In [16]:
ALLOWED_EVALUATION_STRATEGIES

{'flat_multiclass',
 'loss_reweighting',
 'sampling_control',
 'shared_two_head',
 'two_stage_detector'}

In [17]:
df4["eval_strat"] = df4["config_str"].apply(
    lambda s: next((strat for strat in ALLOWED_EVALUATION_STRATEGIES if f"{strat}" in s), None)
)

df4["model_family"] = df4["config_str"].apply(
    lambda s: next((family for family in ALLOWED_MODEL_FAMILIES if f"{family}" in s), None)
)

df4["ast_head"] = df4["config_str"].apply(
    lambda s: next((head for head in AST_HEAD if f"{head}" in s), None)
)

df4["ast_embedding"] = df4["config_str"].apply(
    lambda s: next((emb for emb in AST_EMB if f"{emb}" in s), None)
)

df4["dropout"] = df4["config_str"].apply(
    lambda s: (".".join(re.search(r"dropout_(\d+).(\d+)", s).groups()) if "dropout_" in s else None)
)

df4["kernel_size"] = df4["config_str"].apply(
    lambda s: re.search(r"kernel_(\d+)", s).group(1) if "kernel_" in s else None
)

df4["sd"] = df4["config_str"].apply(
    lambda s: ".".join(re.search(r"sd_(\d+).(\d+)", s).groups()) if "sd_" in s else None
)

df4["head_l2"] = df4["config_str"].apply(
    lambda s: True if "head_l2_True" in s else False if "head_l2_False" in s else None
)

In [18]:
df4

,run_id,phase,metric_phase,epoch,step,checkpoint_path,macro_f1,command_macro_f1,core_command_macro_f1,unknown_f1,...,trial_seed,config_str,eval_strat,model_family,ast_head,ast_embedding,dropout,kernel_size,sd,head_l2
3,113b2e8c8a6e404890dea59f78c58804,phase_4,val,13,15535,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,0,two_stage_detector_trial_01_ast_linear_interp_...,two_stage_detector,ast,linear,interp,0.1,None,None,None
8,1e7c001bf663478fbd092a6b3dcb4f13,phase_4,val,11,13145,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,42,two_stage_detector_trial_01_mlp_mixer_dropout_...,two_stage_detector,mlp_mixer,None,None,0.0,None,None,True
9,2262c543024b4282ba8833a582d0ca2c,phase_4,val,67,80065,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.887161,0.878181,0.878181,0.912908,...,0,sampling_control_trial_01_convnext_sd_0.0_kern...,sampling_control,convnext,None,None,None,7,0.0,None
10,29a88ff4404440b79d09cd58fe294c35,phase_4,val,14,16730,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,2003,two_stage_detector_trial_01_ast_linear_interp_...,two_stage_detector,ast,linear,interp,0.1,None,None,None
18,3566c77f5f2f425fa1a534a827d96241,phase_4,val,41,48995,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,2003,loss_reweighting_trial_01_convnext_sd_0.0_kern...,loss_reweighting,convnext,None,None,None,7,0.0,None
20,38fd557f4b4849fc8a346f6f997fd7ac,phase_4,val,11,13145,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,2003,two_stage_detector_trial_01_convnext_sd_0.0_ke...,two_stage_detector,convnext,None,None,None,7,0.0,None
21,397d06e10d2a4d359b46e475bf1fa02e,phase_4,val,12,14340,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,42,two_stage_detector_trial_01_convnext_sd_0.0_ke...,two_stage_detector,convnext,None,None,None,7,0.0,None
23,3a1cde766ce24ef980333ec97e30c429,phase_4,val,14,16730,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.426804,0.467291,0.467291,0.124853,...,0,sampling_control_trial_01_ast_linear_interp_dr...,sampling_control,ast,linear,interp,0.1,None,None,None
28,3d53cb0c20904980964189c021465e01,phase_4,val,15,17925,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.441933,0.452791,0.452791,0.041339,...,2003,sampling_control_trial_01_ast_linear_interp_dr...,sampling_control,ast,linear,interp,0.1,None,None,None
33,475cf352e4384a3ca748b09a311df5c2,phase_4,val,45,53775,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.733768,0.712809,0.712809,0.713264,...,2003,loss_reweighting_trial_01_ast_linear_interp_dr...,loss_reweighting,ast,linear,interp,0.1,None,None,None
40,5a9d3c36351b4ba896088b09177801b6,phase_4,val,11,13145,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.001384,0.000000,0.000000,0.000000,...,42,loss_reweighting_trial_01_mlp_mixer_dropout_0....,loss_reweighting,mlp_mixer,None,None,0.0,None,None,True
42,5c70cbefffbe4fbeb2f41c615dc29bc8,phase_4,val,18,21510,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.001384,0.000000,0.000000,0.000000,...,2003,loss_reweighting_trial_01_mlp_mixer_dropout_0....,loss_reweighting,mlp_mixer,None,None,0.0,None,None,True
45,61e487b43d6345c8b433b7bde20e5b93,phase_4,val,64,76480,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.873950,0.865468,0.865468,0.902494,...,42,sampling_control_trial_01_convnext_sd_0.0_kern...,sampling_control,convnext,None,None,None,7,0.0,None
46,62b061442fa945c0a1729c76fe49177e,phase_4,val,52,62140,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.774059,0.767035,0.767035,0.818357,...,42,flat_multiclass_trial_01_ast_linear_interp_dro...,flat_multiclass,ast,linear,interp,0.1,None,None,None
49,640a6b8e46a840aba5fefb5b23f37874,phase_4,val,59,70505,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.904645,0.896592,0.896592,0.938602,...,2003,flat_multiclass_trial_01_convnext_sd_0.0_kerne...,flat_multiclass,convnext,None,None,None,7,0.0,None
50,6498809712d44fab8d28abc0a4f0a814,phase_4,val,99,118305,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.810943,0.796420,0.796420,0.847585,...,42,loss_reweighting_trial_01_ast_linear_interp_dr...,loss_reweighting,ast,linear,interp,0.1,None,None,None
52,6bcaa52bd2d04d68917aea0101110d11,phase_4,val,16,19120,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,42,two_stage_detector_trial_01_ast_linear_interp_...,two_stage_detector,ast,linear,interp,0.1,None,None,None
54,6cfac2220ea2448f958f98653bd40f4c,phase_4,val,47,56165,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.885001,0.875238,0.875238,0.929358,...,0,loss_reweighting_trial_01_convnext_sd_0.0_kern...,loss_reweighting,convnext,None,None,None,7,0.0,None
59,71d499e534304b2f989934b45a35ddd3,phase_4,val,11,13145,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,2003,flat_multiclass_trial_01_mlp_mixer_dropout_0.0...,flat_multiclass,mlp_mixer,None,None,0.0,None,None,True
74,8454d270c8994f1b84787c24426ae32d,phase_4,val,37,44215,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.763166,0.746153,0.746153,0.807582,...,2003,flat_multiclass_trial_01_ast_linear_interp_dro...,flat_multiclass,ast,linear,interp,0.1,None,None,None
77,88a2cffe3e1a433395f8f72877ca50bd,phase_4,val,44,52580,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.857688,0.849013,0.849013,0.882582,...,2003,sampling_control_trial_01_convnext_sd_0.0_kern...,sampling_control,convnext,None,None,None,7,0.0,None
78,8c181a4c876846cdb289abca43d00c05,phase_4,val,47,56165,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.766290,0.746947,0.746947,0.806475,...,0,flat_multiclass_trial_01_ast_linear_interp_dro...,flat_multiclass,ast,linear,interp,0.1,None,None,None
79,8d49134f7326434caafa3a2ca1f6ad95,phase_4,val,29,34655,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,42,sampling_control_trial_01_mlp_mixer_dropout_0....,sampling_control,mlp_mixer,None,None,0.0,None,None,True
83,94a0a3d770cc46df92bc35b11d92b181,phase_4,val,11,13145,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.001384,0.000000,0.000000,0.000000,...,0,flat_multiclass_trial_01_mlp_mixer_dropout_0.0...,flat_multiclass,mlp_mixer,None,None,0.0,None,None,True
95,a7e576860d774a39aec0e08f7a54c92e,phase_4,val,22,26290,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.661802,0.658355,0.658355,0.515969,...,0,loss_reweighting_trial_01_ast_linear_interp_dr...,loss_reweighting,ast,linear,interp,0.1,None,None,None
97,ad3b4922ccef45e59fa266df486dd472,phase_4,val,14,16730,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,0,two_stage_detector_trial_01_convnext_sd_0.0_ke...,two_stage_detector,convnext,None,None,None,7,0.0,None
104,c4881ee7990f4a4ebb4964c486c6308d,phase_4,val,41,48995,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.870334,0.862304,0.862304,0.911876,...,42,loss_reweighting_trial_01_convnext_sd_0.0_kern...,loss_reweighting,convnext,None,None,None,7,0.0,None
113,dd91af28f93e4930bccef0cd389d43b6,phase_4,val,11,13145,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.001384,0.000000,0.000000,0.000000,...,0,sampling_control_trial_01_mlp_mixer_dropout_0....,sampling_control,mlp_mixer,None,None,0.0,None,None,True
117,e77f667afe994ce48337624068f751a4,phase_4,val,11,13145,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,42,flat_multiclass_trial_01_mlp_mixer_dropout_0.0...,flat_multiclass,mlp_mixer,None,None,0.0,None,None,True
118,e9233c0f8e3e4e05a43f28672cd3727b,phase_4,val,49,58555,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.905396,0.897134,0.897134,0.942188,...,42,flat_multiclass_trial_01_convnext_sd_0.0_kerne...,flat_multiclass,convnext,None,None,None,7,0.0,None
122,edf4ef0ec68642248798116ca4be2fb2,phase_4,val,20,23900,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,0,two_stage_detector_trial_01_mlp_mixer_dropout_...,two_stage_detector,mlp_mixer,None,None,0.0,None,None,True
124,efd46b1ed29a4a69927bf8d677fdef10,phase_4,val,59,70505,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.917308,0.911274,0.911274,0.955199,...,0,flat_multiclass_trial_01_convnext_sd_0.0_kerne...,flat_multiclass,convnext,None,None,None,7,0.0,None
126,f34252884f1b4df68da2ef6d5f7cfcf0,phase_4,val,13,15535,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,2003,sampling_control_trial_01_mlp_mixer_dropout_0....,sampling_control,mlp_mixer,None,None,0.0,None,None,True
131,fc051d6ab3ee4b329c5f0ff9ee5c8294,phase_4,val,20,23900,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.416455,0.432574,0.432574,0.005055,...,42,sampling_control_trial_01_ast_linear_interp_dr...,sampling_control,ast,linear,interp,0.1,None,None,None
134,fecaf2499ea04e81a9e3f3527571504e,phase_4,val,28,33460,/var/folders/8l/l8x5k0qj70d2ttx81bkn85n40000gn...,0.008542,0.010250,0.010250,0.000000,...,0,loss_reweighting_trial_01_mlp_mixer_dropout_0....,loss_reweighting,mlp_mixer,None,None,0.0,None,None,True

# Save

In [19]:
df1.drop(columns=["checkpoint_path", "trial_config", "config_str"], inplace=True)
df2.drop(columns=["checkpoint_path", "trial_config", "config_str"], inplace=True)
df3.drop(columns=["checkpoint_path", "trial_config", "config_str"], inplace=True)
df4.drop(columns=["checkpoint_path", "trial_config", "config_str"], inplace=True)

In [20]:
df1.to_json("analysis_data/phase_1.json", orient="records", lines=True)
df2.to_json("analysis_data/phase_2.json", orient="records", lines=True)
df3.to_json("analysis_data/phase_3.json", orient="records", lines=True)
df4.to_json("analysis_data/phase_4.json", orient="records", lines=True)

df_per_class.to_json("analysis_data/per_class_metrics.json", orient="records", lines=True)

In [22]:
df4.columns

Index(['run_id', 'phase', 'metric_phase', 'epoch', 'step', 'macro_f1',
       'command_macro_f1', 'core_command_macro_f1', 'unknown_f1', 'silence_f1',
       'macro_f1_nc', 'unknown_to_command_leakage',
       'silence_false_trigger_rate', 'trial_seed', 'eval_strat',
       'model_family', 'ast_head', 'ast_embedding', 'dropout', 'kernel_size',
       'sd', 'head_l2'],
      dtype='object')